/*
 * Copyright 2011 Licel LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package javacardx.crypto;

import com.licel.jcardsim.crypto.AsymmetricCipherImpl;
import com.licel.jcardsim.crypto.SymmetricCipherImpl;
import javacard.security.CryptoException;
import javacard.security.Key;

/**
 * Extension of {@link Cipher} which uses {@link SymmetricCipherImpl}
 * and {@link AsymmetricCipherImpl} to support standard algorithms.
 */
public abstract class Cipher {

        // 模式常數
        public static final byte MODE_ENCRYPT = 1;
        public static final byte MODE_DECRYPT = 2;

        // 演算法常數
        public static final byte ALG_DES_CBC_NOPAD = 1;
        public static final byte ALG_DES_CBC_ISO9797_M1 = 2;
        public static final byte ALG_DES_CBC_ISO9797_M2 = 3;
        public static final byte ALG_DES_CBC_PKCS5 = 4;
        public static final byte ALG_DES_ECB_NOPAD = 5;
        public static final byte ALG_DES_ECB_ISO9797_M1 = 6;
        public static final byte ALG_DES_ECB_ISO9797_M2 = 7;
        public static final byte ALG_DES_ECB_PKCS5 = 8;

        public static final byte ALG_RSA_PKCS1 = 10;
        public static final byte ALG_RSA_ISO14888 = 11;
        public static final byte ALG_RSA_PKCS1_OAEP = 12;
        public static final byte ALG_RSA_NOPAD = 12;

        public static final byte ALG_AES_BLOCK_128_CBC_NOPAD = 13;
        public static final byte ALG_AES_BLOCK_128_ECB_NOPAD = 14;

        // 你的目標演算法
        public static final byte ALG_AES_CBC_PKCS5 = (byte) 110;

        protected Cipher() {
        }

        /**
         * Factory method
         */
        public static Cipher getInstance(byte algorithm, boolean externalAccess)
                        throws CryptoException {

                Cipher instance = null;

                // 1. 非對稱加密
                if (algorithm == ALG_RSA_PKCS1 ||
                                algorithm == ALG_RSA_ISO14888 ||
                                algorithm == ALG_RSA_PKCS1_OAEP ||
                                algorithm == ALG_RSA_NOPAD) {

                        instance = new AsymmetricCipherImpl(algorithm);

                }
                // 2. 對稱加密 (包含我們的新目標)
                else {
                        System.out.println("Cipher getInstance: " + algorithm);
                        instance = new SymmetricCipherImpl(algorithm);
                        System.out.println("Cipher getInstance: " + instance);
                }

                return instance;
        }

        // =============================================================
        // ★★★ 補上這些 Abstract Methods (這就是報錯的原因) ★★★
        // =============================================================

        /**
         * Initializes the <code>Cipher</code> object with the appropriate
         * <code>Key</code>.
         */
        public abstract void init(Key theKey, byte theMode)
                        throws CryptoException;

        /**
         * Initializes the <code>Cipher</code> object with the appropriate
         * <code>Key</code> and algorithm specific parameters.
         */
        public abstract void init(Key theKey, byte theMode, byte[] bArray, short bOff, short bLen)
                        throws CryptoException;

        /**
         * Gets the Algorithm code generated by the <code>getInstance()</code> method.
         */
        public abstract byte getAlgorithm();

        /**
         * Generates encrypted/decrypted output from all/last input data.
         */
        public abstract short doFinal(byte[] inBuff, short inOffset, short inLen, byte[] outBuff, short outOffset)
                        throws CryptoException;

        /**
         * Generates encrypted/decrypted output from input data.
         */
        public abstract short update(byte[] inBuff, short inOffset, short inLen, byte[] outBuff, short outOffset)
                        throws CryptoException;

        // (非必須但建議補上的介面，視版本而定)
        // public abstract byte getPaddingAlgorithm();
        // public abstract byte getCipherAlgorithm();
}